server:
  port: 3100

spring:
  application:
    name: config-server

  profiles:
    active: native, git

  cloud:
    config:
      server:
        #native:
          #search-locations: 'file:///Users/kms/Documents/msa2/project-configs'
        git:
          uri: https://github.com/sparta-hub-5/project-configs
          default-label: main
          search-paths:
            - configs
            - configs/*
          basedir: configs_cache
          clone-on-start: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:3150/eureka/

